base_images:
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
images:
- dockerfile_path: prow/Dockerfile
  to: ocp-qe-perfscale-ci-loaded-upgrade-412to414
promotion:
  to:
  - namespace: ci
    tag: latest
releases:
  intermediate:
    prerelease:
      architecture: amd64
      product: ocp
      version_bounds:
        lower: 4.13.0-0
        upper: 4.14.0-0
  latest:
    release:
      channel: candidate
      version: "4.14"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: perfscale-rosa-multiaz-24nodes-stage-loaded-upgrade414
  cron: 0 8 * * 4
  steps:
    allow_skip_on_success: true
    cluster_profile: aws-perfscale-qe
    env:
      CHANNEL_GROUP: candidate
      CHURN: "false"
      COMPUTE_MACHINE_TYPE: m5.xlarge
      ENABLE_AUTOSCALING: "false"
      GC: "false"
      HOSTED_CP: "false"
      IF_INTERMEDIATE_UPGRADE: "true"
      ITERATION_MULTIPLIER_ENV: "6"
      MULTI_AZ: "true"
      OCM_LOGIN_ENV: staging
      OPENSHIFT_VERSION: "4.12"
      READY_WAIT_TIMEOUT: 30m
      REGION: us-west-2
      REPLICAS: "24"
      USER_COUNT: "30"
    test:
    - as: set-intermediate-releases
      commands: echo "${RELEASE_IMAGE_INTERMEDIATE} ${RELEASE_IMAGE_LATEST}" > ${SHARED_DIR}/perfscale-override-upgrade
        && cat ${SHARED_DIR}/perfscale-override-upgrade
      dependencies:
      - env: RELEASE_IMAGE_INTERMEDIATE
        name: release:intermediate
      from: cli
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    - ref: ipi-install-rbac
    - ref: openshift-cluster-bot-rbac
    - chain: openshift-qe-cluster-density-v2
    - chain: openshift-qe-rosa-loaded-upgrade
    workflow: rosa-aws-sts
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: rosa-4.14-candidate-x86-loaded-upgrade-from-4.12
